#!/usr/bin/env python3
"""Generate EXPERIMENT3_CLOSEOUT.md from the artifacts.

Generated rather than written, because a closeout is mostly numbers and a
hand-copied number goes stale the moment anything is re-run. Every figure below
is read from the artifact that produced it; if an artifact is missing the
document says so instead of omitting the section.

    python scripts/exp3_closeout.py
"""
from __future__ import annotations

import json
import statistics as st
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "exp3"
DOC = ROOT / "EXPERIMENT3_CLOSEOUT.md"


def load(p: Path):
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


def main() -> int:
    census = load(OUT / "stageA_census.json")
    gap = load(OUT / "gap_report.json")
    a2 = load(OUT / "a2_recomputed.json")
    conf = load(ROOT / "outputs" / "exp2b_confirmation.json")
    freeze = load(OUT / "FREEZE_MANIFEST.json")
    val = load(OUT / "validation_result.json")

    L: list[str] = []
    w = L.append
    w("# Experiment 3 — closeout")
    w("")
    w("*Generated by `scripts/exp3_closeout.py` from the artifacts. Every figure "
      "here is read from the file that produced it; nothing is transcribed.*")
    w("")

    if freeze:
        w(f"**Frozen** {freeze['frozen_at']} · generation "
          f"`{freeze['methodology_generation']}` · source `{freeze['source_digest']}` "
          f"· contract `{freeze['contract_digest']}` · {freeze['n_receipts']} receipts")
    else:
        w("**NOT YET FROZEN** — `FREEZE_MANIFEST.json` does not exist. Run "
          "`scripts/exp3_freeze.py --write` once the re-score completes.")
    w("")

    w("## What Experiment 3 asked")
    w("")
    w("Whether local geometry mutations — cheaper and more numerous than "
      "Experiment 2's through-routings — improve the network after frequency "
      "re-optimization inside a fixed vehicle-hour envelope, and whether their "
      "effects compose.")
    w("")

    w("## What went wrong, and what it cost")
    w("")
    w("Phase A1's census and Phase A2's search were both scored under a start "
      "policy the treatment chose. `optimize_frequencies` accepted the "
      "incumbent start only if that plan, once snapped to the headway ladder, "
      "still fit the envelope — and whether it did was decided by the edit: "
      "route-lengthening mutations always failed it, route-shortening "
      "mutations and the unedited control never did. The failing states "
      "silently ran a greedy build instead (**D27**).")
    w("")
    w("The two optimizers do not agree at discovery effort. The control was "
      "the one getting the weaker method, so the treatments were **advantaged**, "
      "not handicapped — the opposite of the first guess.")
    w("")
    w("| effort | incumbent start | greedy | gap | vs the 0.039% floor then in use |")
    w("|---|---|---|---|---|")
    w("| discovery 60000/2/32 | 2,962,743 | 2,956,121 | 0.2240% | **5.7×** |")
    w("| certification 400000/20/0 | 2,956,364 | 2,956,121 | 0.0082% | 0.21× |")
    w("")
    w("Certification effort dissolves it, which is why Experiment 2B's "
      "certified NULL was never in danger and Experiment 3's discovery "
      "ranking was.")
    w("")

    if val:
        w("## Scope of the remediation, measured before it ran")
        w("")
        w(f"A previously-fallback state was already in the basin the corrected "
          f"policy selects, so re-scoring it would change nothing — an "
          f"inference until it was measured. {val['n_states']} stratified "
          f"states across four cardinalities, each run under `greedy` and "
          f"`both`:")
        w("")
        w(f"* maximum |Δ| **{val['max_abs_delta']:.9f}**")
        w(f"* identical frequency-plan hash **{val['identical_plan_hash']}/8**")
        w(f"* `both` selected greedy **{val['both_selected_greedy']}/8**")
        w(f"* `greedy` reproduced the recorded value to "
          f"**{val['max_reproduction_gap']:.9f}**")
        w("")
        w("(**D30**.) The remediation set was therefore exactly the states "
          "*accepted* on the incumbent start. It was later extended to the "
          "whole singles census — not because those numbers were wrong, but "
          "because a state without an execution receipt is not admissible "
          "evidence however correct its number.")
        w("")

    if census:
        w("## The corrected census")
        w("")
        w(f"**{census['n_states']} states compared, {census['n_refused']} "
          f"refused.** Contract `{census['contract']}`, effort "
          f"`{census['effort']}`, start policy `{census['start_policy']}`, "
          f"control {census['control_objective']:.4f}.")
        w("")
        w("**Descriptive only.** " + census["interpretation"])
        w("")
        w("### The floor, and why there isn't one")
        w("")
        w(census["discovery_same_run_floor"])
        w("")
        pk = census.get("per_kind", {})
        if pk:
            w("### By mutation kind — signed effect, no classification")
            w("")
            w("| kind | n | best | median | mean | worst |")
            w("|---|---|---|---|---|---|")
            for k, v in sorted(pk.items(), key=lambda x: x[1]["mean"]):
                w(f"| `{k}` | {v['n']} | {v['best']:+.4f}% | "
                  f"{v['median']:+.4f}% | {v['mean']:+.4f}% | {v['worst']:+.4f}% |")
            w("")
        states = census.get("states", [])
        if states:
            w("### Leaders")
            w("")
            w("| state | k | objective | unserved |")
            w("|---|---|---|---|")
            for r in states[:10]:
                u = r.get("unserved_pct")
                w(f"| `{r['state'][:44]}` | {r['cardinality']} | "
                  f"{r['effect_pct']:+.4f}% | "
                  f"{('%+.4f%%' % u) if u is not None else '—'} |")
            w("")
    else:
        w("## The corrected census")
        w("")
        w("**NOT YET BUILT** — run `scripts/exp3_census.py`.")
        w("")

    if gap:
        w("## What a margin has to clear")
        w("")
        w(f"The heuristic's own error, measured against exhaustive enumeration "
          f"under the production objective across {gap['n_cells']} cells "
          f"(**D33**):")
        w("")
        w(f"* cells with any gap: **{gap['q1_cells_with_gap']} of "
          f"{gap['n_cells']}**")
        w(f"* median {gap['q1_median_gap_pct']:+.6f}%, mean "
          f"{gap['q1_mean_gap_pct']:+.6f}%, max "
          f"**{gap['q1_max_gap_pct']:+.6f}%**")
        w("")
        w("| network | mean gap | max | cells with a gap |")
        w("|---|---|---|---|")
        for n, v in sorted(gap.get("q3_by_network", {}).items()):
            w(f"| `{n}` | {v['mean']:+.6f}% | {v['max']:+.6f}% | {v['nonzero']} |")
        w("")
        w(f"Largest paired control-minus-treatment difference: "
          f"**{gap['q4_max_paired_differential_pct']:.6f} percentage points**.")
        w("")
        w(gap["q4_interpretation"])
        w("")

    if conf:
        w("## Experiment 2B, retested under matched starts")
        w("")
        w("| | unserved effect | floors | verdict |")
        w("|---|---|---|---|")
        w(f"| as recorded, mixed starts | "
          f"{conf['recorded_2b_effect_pct']:+.4f}% | 0.02 | NULL |")
        w(f"| matched starts | {conf['mean_unserved_effect_pct']:+.4f}% | "
          f"{abs(conf['mean_unserved_effect_pct'])/conf['floor_pct']:.2f} | "
          f"**{'NULL' if not conf['measurable'] else 'MEASURABLE'}** |")
        w("")
        w(f"Discovery said {conf['recorded_2b_discovery_pct']:+.4f}%. The "
          f"discovery number was wrong in sign as well as size, and the "
          f"optimizer asymmetry and the effort shortfall pushed the same way. "
          f"(**D31**.)")
        w("")

    if a2:
        w("## Phase A2 — description, not evidence")
        w("")
        w(f"{a2['n_states']} multi-edit states, not re-scored and the search "
          f"not resumed. Correcting the control shifts every effect by "
          f"**{a2['offset_percentage_points']:+.4f} points**:")
        w("")
        w(f"* beating the old control: {a2['states_beating_old_control']}/"
          f"{a2['n_states']}")
        w(f"* beating the corrected control: "
          f"**{a2['states_beating_corrected_control']}/{a2['n_states']}**")
        w(f"* sign flips: **{a2['sign_flips']}/{a2['n_states']}**")
        w("")
        w(a2["admissibility"])
        w("")
        w("**Search disclosure.** " + a2["search_disclosure"])
        w("")

    w("## What Experiment 3 establishes")
    w("")
    w("* Local geometry mutations behave differently from Experiment 2's "
      "expensive through-routings, and the difference is not an artifact of "
      "the evaluator: `splice` ranks near-worst even while receiving the "
      "*better* optimizer.")
    w("* Interactions remain substitutive — a multi-edit state is worth less "
      "than the sum of its members — yet multi-edit states still outperform "
      "the best single, so **single-edit effects may not be summed or ranked "
      "to build a plan**. That is the durable finding, and it does not depend "
      "on the absolute magnitudes that D27 disturbed.")
    w("* Whether any particular margin survives certification is a Stage B "
      "question, and Stage B promotes only from admissible comparisons.")
    w("")
    w("## What it does not establish")
    w("")
    w("* No exhaustive coverage of the mutation space, no global optimum, and "
      "not that every state was reachable. Phase A2 stopped at roughly 131 of "
      "a preregistered 420 evaluations with every state still in lane 1 of 3.")
    w("* No materiality classification. The census is descriptive until a "
      "differential-error bound is adopted; a margin above the measured "
      "0.0018-point differential is **not thereby established**, only not "
      "excluded by that measurement.")
    w("* Nothing about consolidation, which stays deferred under SC-1..SC-4.")
    w("")

    DOC.write_text("\n".join(L) + "\n")
    print(f"wrote {DOC}")
    for name, art in (("census", census), ("gap report", gap),
                      ("2B confirmation", conf), ("A2 recompute", a2),
                      ("freeze manifest", freeze), ("validation", val)):
        print(f"  {name:18s} {'present' if art else 'MISSING'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
